name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe what you'd like and why it would be useful.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Is this related to a frustration with the current app?
      placeholder: I find it difficult to... / It would save time if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature or behavior you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any workarounds or alternative approaches?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Shot Logger
        - Gear Bag
        - Roll Management
        - Film Catalog
        - Export (XMP/CSV/ExifTool)
        - Statistics
        - Sync / Cloud
        - Settings
        - PWA / Offline
        - i18n / Translations
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any mockups, screenshots, or references that help explain the feature.
