/**
 * ExifTool Shell/Batch Script Generator
 *
 * Generates executable scripts that apply EXIF metadata to scan files
 * using ExifTool. Produces both a Unix .sh and a Windows .bat variant.
 */

import { format } from "date-fns";
import { convertGPSPair } from "./utils/gps-converter";
import { formatShutterForXMP } from "./utils/shutter-parser";
import type { ExportInput, ExportOptions } from "./types";

// ---------------------------------------------------------------------------
// Shell escaping
// ---------------------------------------------------------------------------

/**
 * Escape a string for safe use in a single-quoted shell argument.
 * Single quotes are ended, escaped, and re-opened: 'it'\''s' → it's
 */
function shellEscape(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/**
 * Escape a string for safe use in a Windows batch file.
 * Special chars ^, &, |, <, >, (, ), %, ! are escaped with ^.
 */
function batchEscape(value: string): string {
  return value.replace(/"/g, '""').replace(/[&|<>()^%!]/g, "^$&");
}

// ---------------------------------------------------------------------------
// Argument builders
// ---------------------------------------------------------------------------

function buildDescription(
  film: ExportInput["film"],
  roll: ExportInput["roll"],
  frame: ExportInput["frame"],
): string {
  const parts: string[] = [];
  parts.push(`${film.brand} ${film.name}`);

  if (roll.ei !== film.iso) {
    parts.push(`@ EI ${roll.ei} (box ${film.iso})`);
  }

  parts.push(`Frame #${frame.frameNumber}`);

  if (roll.pushPull !== 0) {
    const sign = roll.pushPull > 0 ? "+" : "";
    const label = roll.pushPull > 0 ? "push" : "pull";
    parts.push(`${sign}${roll.pushPull} ${label}`);
  }

  if (frame.notes) {
    parts.push(frame.notes);
  }

  return parts.join(", ");
}

interface ExifToolArgs {
  filename: string;
  flags: string[]; // e.g. ['-Make=Nikon', '-Model=FM2', ...]
}

function buildArgs(input: ExportInput, options: ExportOptions): ExifToolArgs {
  const { frame, roll, camera, lens, film } = input;
  const flags: string[] = [];

  flags.push(`-Make=${camera.make}`);
  flags.push(`-Model=${camera.name}`);

  if (lens) {
    flags.push(`-LensModel=${lens.name}`);
    flags.push(`-FocalLength=${lens.focalLength}`);
  }

  flags.push(`-FNumber=${frame.aperture}`);

  const shutter = formatShutterForXMP(frame.shutterSpeed);
  if (shutter) {
    flags.push(`-ExposureTime=${shutter}`);
  }

  flags.push(`-ISO=${roll.ei}`);

  const dateStr = format(frame.capturedAt, "yyyy:MM:dd HH:mm:ss");
  flags.push(`-DateTimeOriginal=${dateStr}`);

  const gps = convertGPSPair(frame.latitude, frame.longitude);
  if (gps) {
    flags.push(`-GPSLatitude=${gps.latitude}`);
    flags.push(`-GPSLatitudeRef=${gps.latitudeRef}`);
    flags.push(`-GPSLongitude=${gps.longitude}`);
    flags.push(`-GPSLongitudeRef=${gps.longitudeRef}`);
  }

  const description = buildDescription(film, roll, frame);
  flags.push(`-ImageDescription=${description}`);
  flags.push(`-Keywords=${film.brand} ${film.name}`);

  if (options.creatorName) {
    flags.push(`-Creator=${options.creatorName}`);
  }

  if (options.copyright) {
    flags.push(`-Copyright=${options.copyright}`);
  }

  return { filename: input.filename, flags };
}

// ---------------------------------------------------------------------------
// Script generators
// ---------------------------------------------------------------------------

/**
 * Generate a Unix shell script (.sh) with one exiftool command per frame.
 */
export function generateShellScript(
  inputs: ExportInput[],
  options: ExportOptions = {},
): string {
  const lines: string[] = [];

  lines.push("#!/bin/sh");
  lines.push("# Generated by Argent Film Logger");
  lines.push("# Run this script in the directory containing your scan files.");
  lines.push(`# Usage: chmod +x export.sh && ./export.sh`);
  lines.push("");

  for (const input of inputs) {
    const { filename, flags } = buildArgs(input, options);
    const escapedFlags = flags.map((f) => shellEscape(f)).join(" \\\n  ");
    lines.push(
      `exiftool -overwrite_original \\\n  ${escapedFlags} \\\n  ${shellEscape(filename)}`,
    );
    lines.push("");
  }

  lines.push('echo "Done. Metadata written to all files."');

  return lines.join("\n");
}

/**
 * Generate a Windows batch script (.bat) with one exiftool command per frame.
 */
export function generateBatchScript(
  inputs: ExportInput[],
  options: ExportOptions = {},
): string {
  const lines: string[] = [];

  lines.push("@echo off");
  lines.push("REM Generated by Argent Film Logger");
  lines.push("REM Run this script in the directory containing your scan files.");
  lines.push("");

  for (const input of inputs) {
    const { filename, flags } = buildArgs(input, options);
    const escapedFlags = flags
      .map((f) => `"${batchEscape(f)}"`)
      .join(" ^\n  ");
    lines.push(
      `exiftool -overwrite_original ^\n  ${escapedFlags} ^\n  "${batchEscape(filename)}"`,
    );
    lines.push("");
  }

  lines.push("echo Done. Metadata written to all files.");
  lines.push("pause");

  return lines.join("\r\n");
}
